-- MySQL Script generated by MySQL Workbench
-- Sat Aug 15 22:19:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `clube` VARCHAR(100) NULL,
  `rating` INT NULL DEFAULT 1000,
  `jogador` TINYINT NULL,
  `organizador` TINYINT NULL,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_torneios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_torneios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `data` DATE NULL,
  `status` VARCHAR(45) NULL,
  `local` VARCHAR(150) NULL,
  `lim_participantes` INT NULL,
  `arbitro` VARCHAR(45) NULL,
  `organizador_id` INT NOT NULL,
  `num_rodadas` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TB_torneios_TB_usuarios1_idx` (`organizador_id` ASC) VISIBLE,
  CONSTRAINT `fk_TB_torneios_TB_usuarios1`
    FOREIGN KEY (`organizador_id`)
    REFERENCES `mydb`.`TB_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_rodadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_rodadas` (
  `id` INT NOT NULL,
  `numero` INT NOT NULL,
  `data` DATE NULL,
  `status` VARCHAR(45) NULL,
  `torneio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TB_rodadas_TB_torneios1_idx` (`torneio_id` ASC) VISIBLE,
  CONSTRAINT `fk_TB_rodadas_TB_torneios1`
    FOREIGN KEY (`torneio_id`)
    REFERENCES `mydb`.`TB_torneios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_partidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_partidas` (
  `id` INT NOT NULL,
  `resultado` ENUM('0-1', '1-0', '0.5-0.5') NULL,
  `data` DATE NULL,
  `status` VARCHAR(45) NULL,
  `rodada_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TB_partidas_TB_rodadas1_idx` (`rodada_id` ASC) VISIBLE,
  CONSTRAINT `fk_TB_partidas_TB_rodadas1`
    FOREIGN KEY (`rodada_id`)
    REFERENCES `mydb`.`TB_rodadas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_partida_jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_partida_jogador` (
  `partida_id` INT NOT NULL,
  `cor_das_pecas` ENUM('brancas', 'pretas') NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`partida_id`, `usuario_id`),
  INDEX `fk_TB_jogadores_has_TB_partidas_TB_partidas1_idx` (`partida_id` ASC) VISIBLE,
  INDEX `fk_TB_partida_jogador_TB_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_TB_jogadores_has_TB_partidas_TB_partidas1`
    FOREIGN KEY (`partida_id`)
    REFERENCES `mydb`.`TB_partidas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_partida_jogador_TB_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`TB_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_inscricao` (
  `torneio_id` INT NOT NULL,
  `data` DATE NULL,
  `status` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  `rating_inscricao` INT NULL,
  PRIMARY KEY (`torneio_id`, `usuario_id`),
  INDEX `fk_TB_torneios_has_TB_jogadores_TB_torneios1_idx` (`torneio_id` ASC) VISIBLE,
  INDEX `fk_TB_inscricao_TB_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_TB_torneios_has_TB_jogadores_TB_torneios1`
    FOREIGN KEY (`torneio_id`)
    REFERENCES `mydb`.`TB_torneios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_inscricao_TB_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`TB_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
